### ISSUE TITLE
Dúvida relacionada as empresas contratantes

### ISSUE THREAD

**Issue by wschenkel** [lerrua/remote-jobs-brazil#137]
Olá Igor, tudo bem?

Aqui na empresa onde trabalho (http://www.rcadigital.com.br/) nos começamos a adotar essa forma de contratação e alguns meses atrás contratamos 2 devs ruby para trabalhar remoto de SP. Hoje não temos mais vagas abertas para trabalho remoto (ainda). Posso incluir a empresa na lista?

Abraço

**Comment by lerrua** [comment]
@wschenkel pode sim, claro. :wink:
