### ISSUE TITLE
Delete "Happy Bear Software" from the Worldwide companies that hire brazilians to work remotely: list

### ISSUE THREAD

**Issue by eliasmaia** [lerrua/remote-jobs-brazil#140]
@lerrua 

First, I wanted to thank you for the idea of this repository. I wanted to say that it has been helping many people to find jobs and opportunities. Thanks a lot! I had already gone through two interviews from companies I applied to from this list. 

Once in a while I check some companies of this list, and I was checking the Happy Bear Software company website, and I found out that they are not actively working anymore. Apparently the company was shut down. You can check it here: https://www.happybearsoftware.com/happy-bear-software-is-closing-for-business

So I would just suggest to delete the line talking about this company from the list. That's it.  Cheers!

**Comment by lerrua** [comment]
Sure! The PR is already merged, thank you so much @eliasmaia
