### ISSUE TITLE
How to add a new company on the list

### ISSUE THREAD

**Issue by felchs** [lerrua/remote-jobs-brazil#148]
Hello, I'm partner of https://www.clubefii.com.br, I'd like to add my company to the list of remote jobs.

how to do it?

**Comment by rodrigozrusso** [comment]
Hi @felchs,

To add your company, you should:
1. fork the repository
2. Add your company into [README.md](https://github.com/lerrua/remote-jobs-brazil/blob/master/README.md)
3. On your repository, create a [new pull request](https://github.com/lerrua/remote-jobs-brazil/compare), using `lerrua/remote-jobs-brazil/compare` as _base repository_
4. Your pull request will be available for reviewing [here](https://github.com/lerrua/remote-jobs-brazil/pulls)
5. Once it's accepted, your company will be on the list :)

**Comment by felipeaugusto1** [comment]
> Hello, I'm partner of https://www.clubefii.com.br, I'd like to add my company to the list of remote jobs.
> 
> how to do it?

você só precisa editar o arquivo README.md, adicionar a sua empresa e criar um pull request. se precisar de ajuda só.
