### ISSUE TITLE
Vaga Desenvolvedor FullStack Pleno 

### ISSUE THREAD

**Issue by liviacr** [lerrua/remote-jobs-brazil#254]
Somos uma startup de impacto social de Brasília que trabalha com experiência de doação digital. Atualmente trabalhamos através de um aplicativo Android e iOS que conta com uma comunidade de mais de 34 mil usuários que doam de forma rotineira. Recentemente alcançamos o marco de 8 milhões e 700 mil doações realizadas. 
Atualmente nossa equipe trabalha totalmente remota, então não se preocupe em qual região do país você se encontra. Venha fazer parte dessa cultura Ribon. Massa, né?! 

**Descrição da vaga:** 
Nosso time está cada vez mais engajado em trazer a equidade racial para nosso ambiente de trabalho. Para que possamos dar um grande passo nesse trajeto estamos lançando essa vaga exclusiva para pessoas pretas. 
Estamos buscando uma pessoa para trabalhar na área de desenvolvimento da Ribon, hoje temos uma API em Ruby on Rails e um app em React. 

**Requisitos:** 
Experiência com desenvolvimento de testes;
Experiência com desenvolvimento de APIs;
Ser proativo, adaptativo e trabalhar bem com incertezas;
Se auto declarar uma pessoa preta. 

**Diferenciais:** 
Experiência com Ruby on Rails;
Experiência com React;
Experiência de trabalho com designers e metodologias ágeis.

**Responsabilidades:** 
Trabalhar em conjunto com outros designers, desenvolvedores, e equipe de negócios com o objetivo de aumentar a qualidade do serviço oferecido dentro do aplicativo Ribon através de pesquisa com usuários, melhora na entrega de valor do app, ideação de novas features, revisão de features já implementadas, etc.

**Salário:**
Pode variar em torno de R$5.000,00 a R$7.000,00/mês dependendo da sua experiência na área. 

**Por que aplicar?**
Trabalhar em um time de profissionais e investidores diferenciados e multidisciplinares;
Trabalhar projetando soluções para uma ampla base de usuários engajados com o produto e empoderá-los para que ajudem comunidades em situação de extrema pobreza.

Para se inscrever é só entrar nesse[ link](https://app.pipefy.com/public/form/kv0jC__O) :)

**Comment by lerrua** [comment]
@liviacr tudo bem? No caso o repositório é uma lista de empresas que aceitam vagas de trabalho remoto não para o anuncio em si de uma vaga especifica. Sugiro adicionar a empresa na lista e o link da sessão de jobs da empresa por exemplo.
