### ISSUE TITLE
FoxPro opportunity

### ISSUE THREAD

**Issue by albanomah** [lerrua/remote-jobs-brazil#296]
Hi guys, I'm Mariana from CPQI brazil company, we are looking for a good FoxPro developer to work remotely on an international project. This opportunity is full-time CLT. 
I am looking for people who have interest and live in Brazil.
If you are interested, please contact me: malbano@cpqi.com or https://www.linkedin.com/in/mariana-albano-29534856/

**Comment by gabrielmatuk** [comment]
Hello Mariana! 
This repository its to show all company where accepted remote jobs. If you want insert your company into our list =]
