### ISSUE TITLE
Por que não adicionamos o e-mail do recrutador?

### ISSUE THREAD

**Issue by ricardokdz** [lerrua/remote-jobs-brazil#36]
Essa informação nem sempre está clara nos sites das empresas.

Company | Company Website | Contact Email

**Comment by lerrua** [comment]
É uma boa mesmo, ou pelo menos um link referente a futuras vagas. Acho que isso pode entrar nessa issue https://github.com/lerrua/remote-jobs-brazil/issues/23, dentro do json de detalhes da empresa.
