### ISSUE TITLE
A company site seems down

### ISSUE THREAD

**Issue by gehazibispo** [lerrua/remote-jobs-brazil#99]
While trying to access `Agrid | http://www.agrid.com.br/about/`, or even www.agrid.com.br, the domain appeared offline to me.

**Comment by lerrua** [comment]
Thanks for open this issue, I research a little about the company and fixed it using Linkedin profile.

**Comment by gehazibispo** [comment]
Thanks! :)

Em 04/09/2017 4:18 PM, "Igor P. Leroy" <notifications@github.com> escreveu:
